spring:
    application:
        name: root@localhost:3306
    datasource:
        password: 12345
        url: jdbc:mysql://localhost:3306/restaurant_db
        username: root

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
    show-sql: true
